apiVersion: v2
name: wave-operator
description: A Helm chart for Kubernetes
type: application
version: 0.2.3
appVersion: 0.2.3
home: https://github.com/spotinst/charts
icon: https://docs.spot.io/_media/images/spot_mark.png
sources:
- https://github.com/spotinst/wave-operator
keywords:
- spot
- toolkit
- ocean
maintainers:
- name: ntfrnzn
  email: nate.franzen@netapp.com
