apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: wave-issuer
  labels:
  {{- include "wave-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wave-admission-control
  labels:
  {{- include "wave-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - wave-admission-control.{{ .Release.Namespace }}.svc
  - wave-admission-control.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: wave-issuer
  secretName: wave-admission-control-cert
