apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocean-admission-controller.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ocean-admission-controller.controllerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "ocean-admission-controller.controllerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.controller.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- /* controllerLabels includes standard, selector, and custom podLabels */}}
        {{- include "ocean-admission-controller.controllerLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "ocean-admission-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      hostNetwork: {{ .Values.controller.hostNetwork | default false }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .Values.controller.image.repository (.Values.controller.image.tag | default .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "ocean-admission-controller.configMapName" . }}
                optional: true
          volumeMounts:
            - name: tls-certs
              mountPath: {{ .Values.controller.certDir | default "/etc/certs"}}
              readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.controller.httpPort | default 8080 }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.controller.metricsAddr | default ":8082" | trimPrefix ":" }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.controller.metricsAddr | default ":8082" | trimPrefix ":" }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.controller.metricsAddr | default ":8082" | trimPrefix ":" }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ include "ocean-admission-controller.controller.tlsSecretName" . }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
